"""Generate the self-contained Kaggle **kernel** for the biohub-claude champion.

``biohub-cell-tracking-during-development`` is a Kaggle **Code competition** — a
raw ``submission.csv`` file upload is rejected (HTTP 400); the submission must be
produced by a notebook/script kernel that runs against the hidden test set and
writes ``/kaggle/working/submission.csv`` (SOT-1984, cf. the
``kaggle-exec-runtime-gate`` lesson: agent-security had the same constraint).

This script bundles the champion pipeline (the whole ``biohub_tracking`` package,
verbatim, base64-embedded) into one standalone kernel file. The kernel:

1. materialises the package under ``/kaggle/working`` and imports it (no internet,
   no repo filesystem — exactly the exec-compat conditions the gate simulates);
2. finds every ``*.zarr`` test video under ``/kaggle/input`` and runs the champion
   detection+linking pipeline to build ``submission.csv``;
3. on *any* failure (missing data, dependency skew, error) falls back to copying
   ``sample_submission.csv``, so the kernel always emits a valid submission.

Outputs ``submit/kernel/biohub-claude-champion.py`` + ``kernel-metadata.json``,
ready for ``kaggle kernels push -p submit/kernel``.
"""

from __future__ import annotations

import base64
import json
from pathlib import Path

# Package modules to embed, in dependency order. build_submission pulls in
# champion/io/pipeline/detect/link/graph/matching; eval/ is not on that path.
_MODULES = [
    "__init__.py",
    "graph.py",
    "matching.py",
    "detect.py",
    "link.py",
    "io.py",
    "ngff.py",  # dependency-light zarr-v3 reader (kernel image may lack `zarr`)
    "pipeline.py",
    "champion.py",
    "build_submission.py",
]

KERNEL_ID = "sota1111/biohub-claude-champion"
KERNEL_TITLE = "Biohub Claude Champion"
COMPETITION = "biohub-cell-tracking-during-development"

_RUNNER = r'''
"""Biohub-claude champion submission kernel (generated by submit/build_kernel.py).

Self-contained: embeds the biohub_tracking champion pipeline and runs it over the
competition test videos, writing /kaggle/working/submission.csv. Falls back to the
sample submission on any error so the Code-competition run always succeeds.
"""
import base64
import sys
import traceback
from pathlib import Path

WORKING = Path("/kaggle/working")
PKG_ROOT = WORKING / "_biohub_pkg"


def _materialise_package():
    """Write the embedded biohub_tracking package to disk and add to sys.path."""
    pkg_dir = PKG_ROOT / "biohub_tracking"
    pkg_dir.mkdir(parents=True, exist_ok=True)
    for name, blob in EMBEDDED_MODULES.items():
        (pkg_dir / name).write_bytes(base64.b64decode(blob))
    if str(PKG_ROOT) not in sys.path:
        sys.path.insert(0, str(PKG_ROOT))


def _find_test_dir():
    """Locate the directory holding the *.zarr test videos under /kaggle/input."""
    roots = [
        Path("/kaggle/input") / "%(comp)s" / "test",
        Path("/kaggle/input/competitions") / "%(comp)s" / "test",
        Path("/kaggle/input") / "%(comp)s",
        Path("/kaggle/input/competitions") / "%(comp)s",
    ]
    for root in roots:
        if root.is_dir() and any(root.glob("*.zarr")):
            return root
    # Last resort: search anywhere under /kaggle/input for *.zarr videos.
    base = Path("/kaggle/input")
    if base.is_dir():
        for zarr in base.rglob("*.zarr"):
            return zarr.parent
    return None


def _find_sample():
    for cand in (
        Path("/kaggle/input/%(comp)s/sample_submission.csv"),
        Path("/kaggle/input/competitions/%(comp)s/sample_submission.csv"),
    ):
        if cand.exists():
            return cand
    hits = list(Path("/kaggle/input").rglob("sample_submission.csv"))
    return hits[0] if hits else None


def _fallback_to_sample(target: Path, reason: str):
    import shutil
    sample = _find_sample()
    if sample is None:
        raise FileNotFoundError(
            f"champion failed ({reason}) and no sample_submission.csv fallback found"
        )
    shutil.copyfile(sample, target)
    print(f"[fallback] {reason} -> copied {sample} to {target}")


def main():
    target = WORKING / "submission.csv"
    try:
        _materialise_package()
        from biohub_tracking.build_submission import build_submission

        test_dir = _find_test_dir()
        if test_dir is None:
            _fallback_to_sample(target, "no *.zarr test videos found")
            return
        print(f"[champion] building submission from {test_dir}")
        build_submission(test_dir, target)
        rows = sum(1 for _ in open(target)) - 1
        print(f"[champion] wrote {target} ({rows} rows)")
    except Exception as exc:  # noqa: BLE001 - kernel must always emit output
        traceback.print_exc()
        _fallback_to_sample(target, f"champion error: {exc!r}")


if __name__ == "__main__":
    main()
''' % {"comp": COMPETITION}


def build(repo_root: Path) -> Path:
    src = repo_root / "src" / "biohub_tracking"
    embedded = {}
    for name in _MODULES:
        data = (src / name).read_bytes()
        embedded[name] = base64.b64encode(data).decode("ascii")

    out_dir = repo_root / "submit" / "kernel"
    out_dir.mkdir(parents=True, exist_ok=True)

    header = "# Generated by submit/build_kernel.py — do not edit by hand.\n"
    embedded_literal = "EMBEDDED_MODULES = " + json.dumps(embedded, indent=0) + "\n"
    kernel_py = header + embedded_literal + _RUNNER
    kernel_file = out_dir / "biohub-claude-champion.py"
    kernel_file.write_text(kernel_py)

    metadata = {
        "id": KERNEL_ID,
        "title": KERNEL_TITLE,
        "code_file": "biohub-claude-champion.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": True,
        "enable_gpu": False,
        "enable_tpu": False,
        "enable_internet": False,
        "keywords": [],
        "dataset_sources": [],
        "kernel_sources": [],
        "competition_sources": [COMPETITION],
        "model_sources": [],
    }
    (out_dir / "kernel-metadata.json").write_text(json.dumps(metadata, indent=2) + "\n")
    print(f"wrote {kernel_file}")
    print(f"wrote {out_dir / 'kernel-metadata.json'}")
    return kernel_file


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    build(repo_root)


if __name__ == "__main__":
    main()
