"""Generate the self-contained Kaggle **kernel** for the biohub-claude champion.

``biohub-cell-tracking-during-development`` is a Kaggle **Code competition** — a
raw ``submission.csv`` file upload is rejected (HTTP 400); the submission must be
produced by a notebook/script kernel that runs against the hidden test set and
writes ``/kaggle/working/submission.csv`` (SOT-1984, cf. the
``kaggle-exec-runtime-gate`` lesson: agent-security had the same constraint).

This script bundles the champion pipeline (the whole ``biohub_tracking`` package,
verbatim, base64-embedded) into one standalone kernel file. The kernel:

1. materialises the package under ``/kaggle/working`` and imports it (no internet,
   no repo filesystem — exactly the exec-compat conditions the gate simulates);
2. finds every ``*.zarr`` test video under ``/kaggle/input`` and runs the champion
   detection+linking pipeline to build ``submission.csv``;
3. on *any* failure (missing data, dependency skew, error) falls back to copying
   ``sample_submission.csv``, so the kernel always emits a valid submission.

Outputs ``submit/kernel/biohub-claude-champion.py`` + ``kernel-metadata.json``,
ready for ``kaggle kernels push -p submit/kernel``.
"""

from __future__ import annotations

import base64
import json
from pathlib import Path

# Package modules to embed, in dependency order. build_submission pulls in
# champion/io/pipeline/detect/link/graph/matching; eval/ is not on that path.
_MODULES = [
    "__init__.py",
    "graph.py",
    "matching.py",
    "detect.py",
    "link.py",
    "io.py",
    "ngff.py",  # dependency-light zarr-v3 reader (kernel image may lack `zarr`)
    "pipeline.py",
    "champion.py",
    "build_submission.py",
]

KERNEL_ID = "sota1111/biohub-claude-champion"
KERNEL_TITLE = "Biohub Claude Champion"
COMPETITION = "biohub-cell-tracking-during-development"

# Candidate-artifact defaults (SOT-2840): a candidate kernel is an LB-probe build
# that runs a *candidate* config instead of the live champion, written to its own
# kernel id / dir so the reigning champion kernel is never overwritten.
CANDIDATE_KERNEL_ID = "sota1111/biohub-claude-candidate"
CANDIDATE_KERNEL_TITLE = "Biohub Claude Candidate"
CANDIDATE_SUBDIR = "kernel-candidate"
CANDIDATE_CODE_FILE = "biohub-claude-candidate.py"

# Learned-detector kernel defaults (SOT-2847): a GPU kernel that reads pretrained
# weights from an *attached* Kaggle Dataset/Model (internet off) and runs a torch
# learned detector via the default-off receptacle. This is the receptacle build
# path proven by the offline weights-attach smoke test; the champion/candidate
# builds are untouched (no GPU, no torch, no model sources). The verdict this
# path rests on is docs/ai/sot-2847-submission-constraint-verdict.md.
LEARNED_KERNEL_ID = "sota1111/biohub-claude-learned"
LEARNED_KERNEL_TITLE = "Biohub Claude Learned"
LEARNED_SUBDIR = "kernel-learned"
LEARNED_CODE_FILE = "biohub-claude-learned.py"
# The learned kernel additionally embeds the torch receptacle module.
_LEARNED_MODULES = ["learned_detect.py"]

_RUNNER = r'''
"""Biohub-claude champion submission kernel (generated by submit/build_kernel.py).

Self-contained: embeds the biohub_tracking champion pipeline and runs it over the
competition test videos, writing /kaggle/working/submission.csv. Falls back to the
sample submission on any error so the Code-competition run always succeeds.
"""
import base64
import sys
import traceback
from pathlib import Path

WORKING = Path("/kaggle/working")
PKG_ROOT = WORKING / "_biohub_pkg"


def _materialise_package():
    """Write the embedded biohub_tracking package to disk and add to sys.path."""
    pkg_dir = PKG_ROOT / "biohub_tracking"
    pkg_dir.mkdir(parents=True, exist_ok=True)
    for name, blob in EMBEDDED_MODULES.items():
        (pkg_dir / name).write_bytes(base64.b64decode(blob))
    if str(PKG_ROOT) not in sys.path:
        sys.path.insert(0, str(PKG_ROOT))


def _find_test_dir():
    """Locate the directory holding the *.zarr test videos under /kaggle/input."""
    roots = [
        Path("/kaggle/input") / "%(comp)s" / "test",
        Path("/kaggle/input/competitions") / "%(comp)s" / "test",
        Path("/kaggle/input") / "%(comp)s",
        Path("/kaggle/input/competitions") / "%(comp)s",
    ]
    for root in roots:
        if root.is_dir() and any(root.glob("*.zarr")):
            return root
    # Last resort: search anywhere under /kaggle/input for *.zarr videos.
    base = Path("/kaggle/input")
    if base.is_dir():
        for zarr in base.rglob("*.zarr"):
            return zarr.parent
    return None


def _find_sample():
    for cand in (
        Path("/kaggle/input/%(comp)s/sample_submission.csv"),
        Path("/kaggle/input/competitions/%(comp)s/sample_submission.csv"),
    ):
        if cand.exists():
            return cand
    hits = list(Path("/kaggle/input").rglob("sample_submission.csv"))
    return hits[0] if hits else None


def _fallback_to_sample(target: Path, reason: str):
    import shutil
    sample = _find_sample()
    if sample is None:
        raise FileNotFoundError(
            f"champion failed ({reason}) and no sample_submission.csv fallback found"
        )
    shutil.copyfile(sample, target)
    print(f"[fallback] {reason} -> copied {sample} to {target}")


def main():
    target = WORKING / "submission.csv"
    try:
        _materialise_package()
        from biohub_tracking.build_submission import build_submission

        test_dir = _find_test_dir()
        if test_dir is None:
            _fallback_to_sample(target, "no *.zarr test videos found")
            return
        print(f"[champion] building submission from {test_dir}")
        build_submission(test_dir, target)
        rows = sum(1 for _ in open(target)) - 1
        print(f"[champion] wrote {target} ({rows} rows)")
    except Exception as exc:  # noqa: BLE001 - kernel must always emit output
        traceback.print_exc()
        _fallback_to_sample(target, f"champion error: {exc!r}")


if __name__ == "__main__":
    main()
''' % {"comp": COMPETITION}


def _candidate_runner() -> str:
    """The champion runner, plus a preamble that materialises the embedded
    candidate config and points the champion resolver at it (SOT-2840).

    Derived from :data:`_RUNNER` by string-injection so the candidate kernel stays
    byte-for-byte in step with the champion runner logic (only the config source
    differs). The live champion is never mutated — this override sets
    ``BIOHUB_CHAMPION_CONFIG`` for the candidate kernel's own process only.
    """
    install_fn = '''
def _install_candidate_config():
    """Materialise the embedded LB-probe candidate config and point the champion
    resolver at it. Sets BIOHUB_CHAMPION_CONFIG for THIS kernel process only; the
    live champion config is never touched."""
    import os
    import json as _json
    cfg_path = WORKING / "candidate_champion_config.json"
    cfg_path.write_text(_json.dumps(EMBEDDED_CANDIDATE_CONFIG, indent=2))
    os.environ["BIOHUB_CHAMPION_CONFIG"] = str(cfg_path)
    print(f"[candidate] LB-probe config {EMBEDDED_CANDIDATE_CONFIG.get('name')!r} -> {cfg_path}")

'''
    runner = _RUNNER.replace("\ndef main():", install_fn + "\ndef main():", 1)
    runner = runner.replace(
        "        _materialise_package()\n",
        "        _materialise_package()\n        _install_candidate_config()\n",
        1,
    )
    return runner


def build(
    repo_root: Path,
    *,
    candidate_config: dict | None = None,
    kernel_id: str | None = None,
    kernel_title: str | None = None,
    out_subdir: str | None = None,
    code_file: str | None = None,
    learned: bool = False,
    enable_gpu: bool | None = None,
    model_sources: list[str] | None = None,
    dataset_sources: list[str] | None = None,
) -> Path:
    """Build the champion kernel, or (when *candidate_config* is given) an
    LB-probe candidate kernel that runs *candidate_config* instead of the live
    champion. The champion path is unchanged and byte-identical to before.

    ``learned=True`` (SOT-2847) builds a **learned-detector** kernel: it embeds
    the torch receptacle module, enables GPU by default, and declares the attached
    weights via ``model_sources``/``dataset_sources`` (read offline, internet off).
    Compose it with *candidate_config* to point ``BIOHUB_CHAMPION_CONFIG`` at a
    config that enables the ``learned_detector`` block. The champion and candidate
    builds keep ``learned=False`` (no GPU, no torch, no model sources)."""
    is_candidate = candidate_config is not None
    kernel_id = kernel_id or (
        LEARNED_KERNEL_ID
        if learned
        else (CANDIDATE_KERNEL_ID if is_candidate else KERNEL_ID)
    )
    kernel_title = kernel_title or (
        LEARNED_KERNEL_TITLE
        if learned
        else (CANDIDATE_KERNEL_TITLE if is_candidate else KERNEL_TITLE)
    )
    out_subdir = out_subdir or (
        LEARNED_SUBDIR if learned else (CANDIDATE_SUBDIR if is_candidate else "kernel")
    )
    code_file = code_file or (
        LEARNED_CODE_FILE
        if learned
        else (CANDIDATE_CODE_FILE if is_candidate else "biohub-claude-champion.py")
    )

    src = repo_root / "src" / "biohub_tracking"
    modules = list(_MODULES) + (_LEARNED_MODULES if learned else [])
    embedded = {}
    for name in modules:
        data = (src / name).read_bytes()
        embedded[name] = base64.b64encode(data).decode("ascii")

    out_dir = repo_root / "submit" / out_subdir
    out_dir.mkdir(parents=True, exist_ok=True)

    header = "# Generated by submit/build_kernel.py — do not edit by hand.\n"
    embedded_literal = "EMBEDDED_MODULES = " + json.dumps(embedded, indent=0) + "\n"
    if is_candidate:
        # Embed the config as a JSON *string* parsed at import time, NOT as a bare
        # Python literal: json.dumps emits JSON booleans/null (false/true/null) which
        # are NameErrors when pasted as a Python expression. Round-tripping through
        # json.loads keeps the exact validated config and stays valid Python.
        candidate_literal = (
            "EMBEDDED_CANDIDATE_CONFIG = __import__('json').loads(\n    "
            + repr(json.dumps(candidate_config))
            + "\n)\n"
        )
        kernel_py = header + embedded_literal + candidate_literal + _candidate_runner()
    else:
        kernel_py = header + embedded_literal + _RUNNER
    kernel_file = out_dir / code_file
    kernel_file.write_text(kernel_py)

    metadata = {
        "id": kernel_id,
        "title": kernel_title,
        "code_file": code_file,
        "language": "python",
        "kernel_type": "script",
        "is_private": True,
        # Learned kernel runs torch on GPU; champion/candidate stay CPU-only.
        "enable_gpu": bool(enable_gpu) if enable_gpu is not None else bool(learned),
        "enable_tpu": False,
        # Internet MUST stay off for a Code-competition submission; the weights
        # come from the attached (offline) model/dataset sources instead.
        "enable_internet": False,
        "keywords": [],
        "dataset_sources": list(dataset_sources or []),
        "kernel_sources": [],
        "competition_sources": [COMPETITION],
        "model_sources": list(model_sources or []),
    }
    (out_dir / "kernel-metadata.json").write_text(json.dumps(metadata, indent=2) + "\n")
    print(f"wrote {kernel_file}")
    print(f"wrote {out_dir / 'kernel-metadata.json'}")
    return kernel_file


def build_candidate(repo_root: Path, config_path: Path | str, **kwargs) -> Path:
    """Build an LB-probe candidate kernel from a candidate config JSON file."""
    with open(config_path) as fh:
        candidate_config = json.load(fh)
    return build(repo_root, candidate_config=candidate_config, **kwargs)


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--candidate-config",
        type=Path,
        default=None,
        help=(
            "Build an LB-probe CANDIDATE kernel that runs this champion-config JSON "
            "instead of the live champion (live champion kernel untouched)."
        ),
    )
    parser.add_argument("--kernel-id", default=None, help="Override the kernel id.")
    parser.add_argument("--kernel-title", default=None, help="Override the kernel title.")
    parser.add_argument(
        "--out-subdir", default=None, help="Output subdir under submit/ (default: kernel)."
    )
    parser.add_argument("--code-file", default=None, help="Output kernel .py filename.")
    parser.add_argument(
        "--learned",
        action="store_true",
        help=(
            "Build a LEARNED-detector GPU kernel (SOT-2847 receptacle): embeds the "
            "torch module, enables GPU, reads attached offline weights. Compose "
            "with --candidate-config to enable the learned_detector block."
        ),
    )
    parser.add_argument(
        "--model-source",
        action="append",
        default=None,
        help="Attached Kaggle Model source (offline weights); repeatable.",
    )
    parser.add_argument(
        "--dataset-source",
        action="append",
        default=None,
        help="Attached Kaggle Dataset source (offline weights); repeatable.",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    build(
        repo_root,
        candidate_config=(
            json.loads(args.candidate_config.read_text())
            if args.candidate_config is not None
            else None
        ),
        kernel_id=args.kernel_id,
        kernel_title=args.kernel_title,
        out_subdir=args.out_subdir,
        code_file=args.code_file,
        learned=args.learned,
        model_sources=args.model_source,
        dataset_sources=args.dataset_source,
    )


if __name__ == "__main__":
    main()
